### ISSUE TITLE
SAML Support

### ISSUE THREAD

**Issue by romanblachman** [mobilabsolutions/jenkins-ios#28]
Allow login using SAML SSO (e.g. Azure AD).

**Comment by mobi-robert** [comment]
Hey @romanblachman,
thanks for your suggestion. Is there any SAML plugin that you think the application should support in particular? [This one](https://wiki.jenkins.io/display/JENKINS/SAML+Plugin) seems to be the most referenced online.

**Comment by romanblachman** [comment]
Hello,

Yes, that’s the plugin we are using to authenticate to our Jenkins instance using Azure AD.

Today you only support username / password authentication?

Thanks,
Roman

**Comment by mobi-robert** [comment]
Yes, that's correct. If your Jenkins instance is world-readable it should also be possible to define a token that can then be used to trigger builds. I doubt that is your case, though.
As for integrating other authentication methods, I think that this is definitely something worth considering. I will have to do some research into how the plugin affects the API first, though.

Best,
Robert

**Comment by romanblachman** [comment]
Thank you Robert! I really liked the idea of having an app for Jenkins on my iPhone so SAML authentication would be really awesome to have. Let me know if can provide any info that could help integrate with this.

Thanks,
Roman

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mobi-robert** [comment]
Hey @romanblachman, sorry for not following up on this earlier, I have been very busy with other projects as well as the redesign of the application.

I just got SAML up and working on our local Jenkins instance (albeit with Google and not Azure AD). I think the easiest way to authenticate with Jenkins in a SAML configuration is using an API Token ([see here](https://support.cloudbees.com/hc/en-us/articles/115003090592-How-to-re-generate-my-Jenkins-user-token)). That way, not only SAML but many other authentication mechanisms are supported (e.g. GitHub, using Google directly, ...). 

To me, it is unclear whether or not implementing SAML support in the native application is even possible without having access to all of the authentication parameters that need to be specified when setting it up.

It would be great if you could let me know whether or not the API Token solution works for you.

Best, 
Robert

**Comment by romanblachman** [comment]
@mobi-robert hello, it actually helped a lot! I was able to configure the app on my phone finally, using the API Tokens support.

Just one thing to notice, when working with Azure AD plugin for authentication, it is important to add the permission for the UPN as stated in the plugin documentation https://wiki.jenkins.io/display/JENKINS/Azure+AD+Plugin and issues like https://github.com/jenkinsci/azure-ad-plugin/issues/16 and https://issues.jenkins-ci.org/browse/JENKINS-54115.

It took me a while to figure out why I was getting forbidden errors when using the correct username and API token...

Thank you for this great app!

Do you have plans for adding push notifications in the future?

**Comment by mobi-robert** [comment]
@romanblachman I'm glad to hear that it works now! For now, we don't have any active plans to add push notifications in the future, but we will definitely keep it in mind. I think there might be some technical issues that make this hard (e.g. it is at least not easily possible to periodically check a status on the device and remote notifications require an APNS certificate which is a problem if we wanted to trigger the notifications from individual Jenkins instances). 

Any ideas on how this could be handled (or of course also any PR) would be greatly appreciated 😄.
