### ISSUE TITLE
build button is always disabled for all projects

### ISSUE THREAD

**Issue by leabdalla** [mobilabsolutions/jenkins-ios#73]
I can't build any project using the app cause the Build button is always disabled.

What is the reason for that?

**Comment by mobi-robert** [comment]
Just to make sure, are you able to navigate a job's information (so see last builds, etc.) in the app? If not, there might be an issue with your reverse proxy setup (Jenkins > Manage Jenkins > Configure System > Jenkins Location > Jenkins URL).

**Comment by leabdalla** [comment]
I can see only the last build number and date. When I click to see its logs it takes forever with spinner loading and shows "The quest timed out".

The Other Builds list shows zero.

**Comment by mobi-robert** [comment]
This does sound like your Jenkins reverse proxy setup has an issue. Could you check whether the expected URL is set at Jenkins > Manage Jenkins > Configure System > Jenkins Location > Jenkins URL on your Jenkins instance?

**Comment by leabdalla** [comment]
That's the tricky, you owned! The Location URL was wrong.

Thanks!
